import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import 'bootstrap/dist/css/bootstrap.min.css';
import { HeaderPage}  from '@/app/components/header'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='h-[56px] flex justify-center item-center bg-violet-900'>
          <Link href='/' className="rounded-lg px-3 py-2 text-green-50 font-medium hover:bg-slate-100 hover:text-slate-900">Home</Link>
          <Link href='/productos' className="rounded-lg px-3 py-2 text-green-50 font-medium hover:bg-slate-100 hover:text-slate-900">Productos</Link>
          <Link href='/acercade' className="rounded-lg px-3 py-2 text-green-50 font-medium hover:bg-slate-100 hover:text-slate-900">Acerca de</Link>
          <HeaderPage/>
        </nav>
            
        {children}
        
        </body>
    </html>
  )
}